apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
    app.kubernetes.io/part-of: hacbsqeapp
  name: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
  namespace: jinqi-1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d626a267821b0ce70494c77afcc826c2d4c819aadeff88af9a55e27bfeb70ff6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
