apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
    app.kubernetes.io/part-of: hacbsqeapp
  name: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
  namespace: jinqi-1-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hacbsqeapp-devfile-sample-python-basic-lkpk-sample
    weight: 100
status: {}
